
###
POST http://localhost:8080/clients
Content-Type: application/json

{
    "name": "HRT",
    "login": "RTH",
    "password": "paRTH",
    "email": "olRTHg@GMAIL.com"
}

###
GET http://localhost:8080/clients/381172

###
DELETE localhost:8080/clients/234

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Морковь",
  "price": 60,
  "amount": 1
}

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 5,
  "name": "Абрикос",
  "price": 70,
  "amount": 2
}

###
DELETE localhost:8080/products/5

###
GET localhost:8080/clients
Content-Type: application/json

{
  "id": 1,
  "name": "Банан",
  "price": 80
}

###
GET http://localhost:8080/products/221601

###
GET http://localhost:8080/products?name=Морковь

###
POST http://localhost:8080/carts/641999/823957

###
PUT http://localhost:8080/carts/641999
Content-Type: application/json

{
  "id": 823957,
  "amount": 2
}


###
DELETE localhost:8080/carts/641999/13463

###
POST http://localhost:8080/payments/286582




