
###
POST localhost:8080/clients
Content-Type: application/json

{
    "name": "HRT",
    "login": "RTH",
    "password": "paRTH",
    "email": "olRTHg@GMAIL.com"
}

###
GET localhost:8080/clients/234

###
DELETE localhost:8080/clients/234

###
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Морковь",
  "price": 60,
  "amount": 1
}

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 5,
  "name": "Абрикос",
  "price": 70,
  "amount": 2
}

###
DELETE localhost:8080/products/5

###
GET localhost:8080/clients
Content-Type: application/json

{
  "id": 1,
  "name": "Банан",
  "price": 80
}

###
GET localhost:8080/products/1

###
GET localhost:8080/products?name=Морковь

###
POST localhost:8080/carts/45645/13463

###
PUT localhost:8080/carts/454547/4324
Content-Type: application/json

{
  "amount": 2
}


###
DELETE localhost:8080/carts/45645/13463

###
POST localhost:8080/payments/45645



